/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.tm

import org.junit.Test

class FifoTaskManagerTest : BaseTest() {
    override fun initClassUnderTest(): AbstractTaskManager {
        return FifoTaskManager()
    }

    @Test
    fun whenTaskManagerIsNotFullAdditionShouldBeSuccessful() {
        // Given
        val p1 = Process(1, Priority.Medium, classUnderTest)
        // Expect
        assert(classUnderTest.add(p1))
        assert(classUnderTest.tasks.size == 1)
    }

    @Test
    fun whenTaskManagerIsNotFullAddReturnsFalse() {
        // Given
        for (i in 1 until PROCESS_LIMIT + 1) {
            classUnderTest.add(Process(i.toLong(), Priority.Medium, classUnderTest))
        }
        val p11 = Process(PROCESS_LIMIT + 1.toLong(), Priority.Medium, classUnderTest)
        // Expect
        assert(classUnderTest.add(p11))
        assert(classUnderTest.tasks.size == PROCESS_LIMIT)
        assert(classUnderTest.tasks.contains(p11))
        assert(classUnderTest.tasks.none { it.ID.toInt() == 1 })
    }
}
