/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.tm

import org.junit.Test

class TaskManagerTest : BaseTest() {
    override fun initClassUnderTest(): AbstractTaskManager {
        return TaskManager()
    }

    @Test
    fun whenTaskManagerIsNotFullAddReturnsTrue() {
        // Given
        val p1 = Process(1, Priority.Medium, classUnderTest)
        // Expect
        assert(classUnderTest.add(p1))
    }

    @Test
    fun whenTaskManagerIsNotFullAddReturnsFalse() {
        // Given
        for (i in 1 until PROCESS_LIMIT + 1) {
            classUnderTest.add(Process(i.toLong(), Priority.Medium, classUnderTest))
        }
        val p1 = Process(PROCESS_LIMIT + 1.toLong(), Priority.Medium, classUnderTest)
        // Expect
        assert(!classUnderTest.add(p1))
    }

}
